---
datasets:
  - sift-1m
common_params:
  numQueriesToRun: 1000
  numWarmUpQueries: 20
  samplingRate: 2
  flushFreq: 500000
  topK: 100
  efSearch: 150
  queryThreads: 1
  createIndexInMemory: false
  cleanIndexDirectory: true
  saveResultsOnDisk: true

algorithms:
  CAGRA_HNSW:
    cuvsIndexDirPath: "cuvsIndex"
    cagraGraphDegree: [32, 48]
    cagraIntermediateGraphDegree: [64, 96]
    cuvsWriterThreads: [4, 8]
    numIndexThreads: [8]

  LUCENE_HNSW:
    hnswIndexDirPath: "hnswIndex"
    hnswMaxConn: [32, 64]
    hnswBeamWidth: [128, 256]
    numIndexThreads: [8]



